### ISSUE TITLE
Unable to run the demo on local machine

### ISSUE THREAD

**Issue by vijaysagi1** [SummitKwan/transparent_latent_gan#16]
Hi,

As per your instruction i downloaded the  code and ran the from the command prompt. The following is the error encountered:

 deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 17, in <module>
  File "src/tl_gan/feature_axis.py", line 15
SyntaxError: Non-ASCII character '\xe2' in file src/tl_gan/feature_axis.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Pls suggest the way forward

FYI:
Python version 2.7
tensorflow version 1.7.0

Thanks

**Comment by SummitKwan** [comment]
Hi vijaysagi1,
Thank you for your feedback.  This error is because of that Python 3 and Python 2 handle string differently, and this project is developed in a short time and currently only support Python3 (tested on Python 3.6).  It would be great if you have a Python 3 environment and test it out.  Or if necessary, I could deliver a docker image with Python 3 environment in it.
